### ISSUE TITLE
can't find plugin

### ISSUE THREAD

**Issue by Para96** [hyacz/decky-zerotier#18]
I can't find the plugin on decky version 3.0.1 stable using steamos stable branch. Am I missing something?

**Comment by hyacz** [comment]
This plugin has not been officially merged by the decky maintenance team and is currently only available for download in the test store channel. v0.2.0 uses remote_binary, you may encounter network problems during installation. You can also manually install the v0.1.0 version (https://github.com/hyacz/decky-zerotier/releases/download/v0.1.0/decky-zerotier.zip)
